version: '3.1'

services:

  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres2
    restart: unless-stopped
    image: postgres
    ports:
      - "54832:5432"
      - "5432:5432"
